apiVersion: v1
kind: ResourceQuota

metadata:
  name: student-k8s-quota
  namespace: student-k8s

spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    pods: "5"