apiVersion: v1
kind: Service

metadata:
  name: student-k8s-service
  namespace: student-k8s

spec:
  type: LoadBalancer

  selector:
    app: student-k8s-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000